// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddGroup(arg1, arg2) {
  return window['go']['main']['App']['AddGroup'](arg1, arg2);
}

export function AddService(arg1) {
  return window['go']['main']['App']['AddService'](arg1);
}

export function AddServiceToGroup(arg1, arg2) {
  return window['go']['main']['App']['AddServiceToGroup'](arg1, arg2);
}

export function Browse(arg1, arg2, arg3) {
  return window['go']['main']['App']['Browse'](arg1, arg2, arg3);
}

export function ClearLogs(arg1) {
  return window['go']['main']['App']['ClearLogs'](arg1);
}

export function DeleteService(arg1) {
  return window['go']['main']['App']['DeleteService'](arg1);
}

export function EmitToFrontend(arg1, arg2, arg3) {
  return window['go']['main']['App']['EmitToFrontend'](arg1, arg2, arg3);
}

export function GetGroups() {
  return window['go']['main']['App']['GetGroups']();
}

export function GetLaunchProfiles(arg1) {
  return window['go']['main']['App']['GetLaunchProfiles'](arg1);
}

export function GetService(arg1) {
  return window['go']['main']['App']['GetService'](arg1);
}

export function GetServices() {
  return window['go']['main']['App']['GetServices']();
}

export function ImportProject(arg1, arg2, arg3) {
  return window['go']['main']['App']['ImportProject'](arg1, arg2, arg3);
}

export function ImportSLN(arg1) {
  return window['go']['main']['App']['ImportSLN'](arg1);
}

export function ReloadServices() {
  return window['go']['main']['App']['ReloadServices']();
}

export function StartGroup(arg1) {
  return window['go']['main']['App']['StartGroup'](arg1);
}

export function StartService(arg1) {
  return window['go']['main']['App']['StartService'](arg1);
}

export function StartServiceWithoutBuild(arg1) {
  return window['go']['main']['App']['StartServiceWithoutBuild'](arg1);
}

export function StopService(arg1) {
  return window['go']['main']['App']['StopService'](arg1);
}

export function UpdateGroup(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateGroup'](arg1, arg2, arg3);
}

export function UpdateService(arg1, arg2) {
  return window['go']['main']['App']['UpdateService'](arg1, arg2);
}

export function UpdateServiceInGroup(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateServiceInGroup'](arg1, arg2, arg3);
}
