// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {process} from '../models';
import {config} from '../models';
import {service} from '../models';

export function AddGroup(arg1:string,arg2:process.ServiceEnv):Promise<string>;

export function AddService(arg1:config.ServiceConfig):Promise<service.Service>;

export function AddServiceToGroup(arg1:string,arg2:config.ServiceConfig):Promise<string>;

export function Browse(arg1:string,arg2:string,arg3:string):Promise<string>;

export function ClearLogs(arg1:string):Promise<void>;

export function DeleteService(arg1:string):Promise<void>;

export function EmitToFrontend(arg1:string,arg2:string,arg3:any):Promise<void>;

export function GetGroups():Promise<Record<string, config.GroupConfig>>;

export function GetLaunchProfiles(arg1:string):Promise<Array<string>>;

export function GetService(arg1:string):Promise<service.ServiceInfo>;

export function GetServices():Promise<Record<string, service.ServiceInfo>>;

export function ImportProject(arg1:string,arg2:string,arg3:string):Promise<void>;

export function ImportSLN(arg1:string):Promise<void>;

export function ReloadServices():Promise<void>;

export function RestartService(arg1:string):Promise<void>;

export function StartGroup(arg1:string):Promise<void>;

export function StartService(arg1:string):Promise<void>;

export function StartServiceWithoutBuild(arg1:string):Promise<void>;

export function StopService(arg1:string):Promise<void>;

export function UpdateGroup(arg1:string,arg2:string,arg3:process.ServiceEnv):Promise<void>;

export function UpdateService(arg1:string,arg2:config.ServiceConfig):Promise<service.Service>;

export function UpdateServiceInGroup(arg1:string,arg2:string,arg3:config.ServiceConfig):Promise<void>;
